import type { Power, Territory, UnitId, PowerId } from "./types.js";

export const POWERS: Record<PowerId, Power> = {
  russia: { id: "russia", name: "Russia", alliance: "allies", color: "#a33032", accent: "#6e1d1e", capital: "russia", turnOrder: 1 },
  germany: { id: "germany", name: "Germany", alliance: "axis", color: "#6a6a6a", accent: "#3a3a3a", capital: "germany_terr", turnOrder: 2 },
  uk: { id: "uk", name: "United Kingdom", alliance: "allies", color: "#c6a24f", accent: "#7c6327", capital: "united_kingdom", turnOrder: 3 },
  japan: { id: "japan", name: "Japan", alliance: "axis", color: "#e39a46", accent: "#8a5618", capital: "japan", turnOrder: 4 },
  usa: { id: "usa", name: "United States", alliance: "allies", color: "#3e7a5c", accent: "#1f3d2e", capital: "eastern_united_states", turnOrder: 5 },
};

export const POWER_ORDER: PowerId[] = ["russia", "germany", "uk", "japan", "usa"];

/**
 * TERRITORIES — Axis & Allies 1942 2E complete territory list.
 * Coordinates from TripleA world_war_ii_v5_1942 map-geo.ts centroids.
 * Adjacency from TripleA WW2v5_1942_2nd_TR.xml.
 */
export const TERRITORIES: Territory[] = [
  // ========= LAND TERRITORIES =========
  { id: "russia", name: "Russia", terrain: "land", ipc: 8, originalOwner: "russia",
    x: 1814, y: 297, neighbors: ["archangel","caucasus","kazakh","novosibirsk","vologda","west_russia"] },
  { id: "karelia", name: "Karelia", terrain: "land", ipc: 2, originalOwner: "russia",
    x: 1351, y: 232, neighbors: ["archangel","baltic_states","belorussia","finland","sz_4","sz_5","west_russia"] },
  { id: "ukraine", name: "Ukraine", terrain: "land", ipc: 2, originalOwner: "russia",
    x: 1431, y: 624, neighbors: ["balkans","belorussia","caucasus","poland","sz_16","west_russia"] },
  { id: "caucasus", name: "Caucasus", terrain: "land", ipc: 4, originalOwner: "russia",
    x: 1589, y: 595, neighbors: ["kazakh","persia","russia","sz_16","turkey","ukraine","west_russia"] },
  { id: "archangel", name: "Archangel", terrain: "land", ipc: 1, originalOwner: "russia",
    x: 1600, y: 224, neighbors: ["evenki","karelia","russia","sz_4","vologda","west_russia"] },
  { id: "vologda", name: "Vologda", terrain: "land", ipc: 2, originalOwner: "russia",
    x: 2049, y: 227, neighbors: ["archangel","evenki","novosibirsk","russia"] },
  { id: "west_russia", name: "W. Russia", terrain: "land", ipc: 2, originalOwner: "russia",
    x: 1609, y: 416, neighbors: ["archangel","belorussia","caucasus","karelia","russia","ukraine"] },
  { id: "belorussia", name: "Belorussia", terrain: "land", ipc: 2, originalOwner: "russia",
    x: 1434, y: 442, neighbors: ["baltic_states","karelia","poland","ukraine","west_russia"] },
  { id: "baltic_states", name: "Baltic States", terrain: "land", ipc: 2, originalOwner: "russia",
    x: 1247, y: 368, neighbors: ["belorussia","germany_terr","karelia","poland","sz_5"] },
  { id: "evenki", name: "Evenki", terrain: "land", ipc: 1, originalOwner: "russia",
    x: 2182, y: 286, neighbors: ["archangel","mongolia","novosibirsk","sinkiang","vologda","yakut"] },
  { id: "novosibirsk", name: "Novosibirsk", terrain: "land", ipc: 1, originalOwner: "russia",
    x: 1955, y: 520, neighbors: ["evenki","kazakh","russia","sinkiang","vologda"] },
  { id: "yakut", name: "Yakut", terrain: "land", ipc: 1, originalOwner: "russia",
    x: 2347, y: 244, neighbors: ["buryatia","evenki","mongolia","soviet_far_east"] },
  { id: "buryatia", name: "Buryatia", terrain: "land", ipc: 1, originalOwner: "russia",
    x: 2581, y: 366, neighbors: ["manchuria","mongolia","soviet_far_east","sz_62","sz_63","yakut"] },
  { id: "soviet_far_east", name: "Soviet Far East", terrain: "land", ipc: 1, originalOwner: "russia",
    x: 2711, y: 131, neighbors: ["buryatia","sz_63","yakut"] },
  { id: "sinkiang", name: "Sinkiang", terrain: "land", ipc: 1, originalOwner: "russia",
    x: 2114, y: 676, neighbors: ["anhwei","evenki","kazakh","mongolia","novosibirsk","szechwan"] },
  { id: "mongolia", name: "Mongolia", terrain: "land", ipc: 0, originalOwner: "russia",
    x: 2267, y: 542, neighbors: ["anhwei","buryatia","evenki","manchuria","sinkiang","yakut"] },
  { id: "kazakh", name: "Kazakh", terrain: "land", ipc: 2, originalOwner: "russia",
    x: 1800, y: 724, neighbors: ["afghanistan","caucasus","novosibirsk","persia","russia","sinkiang","szechwan"] },
  { id: "germany_terr", name: "Germany", terrain: "land", ipc: 10, originalOwner: "germany",
    x: 1067, y: 568, neighbors: ["balkans","baltic_states","france","italy","northern_europe","poland","southern_europe","switzerland","sz_5"] },
  { id: "northern_europe", name: "N. Europe", terrain: "land", ipc: 2, originalOwner: "germany",
    x: 894, y: 482, neighbors: ["france","germany_terr","sz_5","sz_6","sz_8"] },
  { id: "southern_europe", name: "S. Europe", terrain: "land", ipc: 2, originalOwner: "germany",
    x: 1136, y: 800, neighbors: ["balkans","germany_terr","italy","sz_15","turkey"] },
  { id: "france", name: "France", terrain: "land", ipc: 6, originalOwner: "germany",
    x: 802, y: 656, neighbors: ["germany_terr","italy","northern_europe","spain_portugal","switzerland","sz_14","sz_8"] },
  { id: "poland", name: "Poland", terrain: "land", ipc: 2, originalOwner: "germany",
    x: 1275, y: 528, neighbors: ["balkans","baltic_states","belorussia","germany_terr","ukraine"] },
  { id: "italy", name: "Italy", terrain: "land", ipc: 3, originalOwner: "germany",
    x: 988, y: 783, neighbors: ["france","germany_terr","southern_europe","switzerland","sz_15"] },
  { id: "norway", name: "Norway", terrain: "land", ipc: 2, originalOwner: "germany",
    x: 997, y: 226, neighbors: ["finland","sweden","sz_3","sz_5","sz_6"] },
  { id: "finland", name: "Finland", terrain: "land", ipc: 1, originalOwner: "germany",
    x: 1190, y: 200, neighbors: ["karelia","norway","sweden","sz_3","sz_5"] },
  { id: "balkans", name: "Balkans", terrain: "land", ipc: 2, originalOwner: "germany",
    x: 1268, y: 735, neighbors: ["germany_terr","poland","southern_europe","sz_16","turkey","ukraine"] },
  { id: "sweden", name: "Sweden", terrain: "land", ipc: 0, originalOwner: undefined,
    x: 1065, y: 323, neighbors: ["finland","norway","sz_5"] },
  { id: "switzerland", name: "Switzerland", terrain: "land", ipc: 0, originalOwner: undefined,
    x: 956, y: 690, neighbors: ["france","germany_terr","italy"] },
  { id: "spain_portugal", name: "Spain/Portugal", terrain: "land", ipc: 0, originalOwner: undefined,
    x: 636, y: 822, neighbors: ["france","gibraltar","sz_13","sz_14"] },
  { id: "eire", name: "Eire", terrain: "land", ipc: 0, originalOwner: "uk",
    x: 720, y: 288, neighbors: ["sz_7","sz_8","united_kingdom"] },
  { id: "gibraltar", name: "Gibraltar", terrain: "land", ipc: 0, originalOwner: "uk",
    x: 703, y: 902, neighbors: ["spain_portugal","sz_13","sz_14"] },
  { id: "iceland", name: "Iceland", terrain: "land", ipc: 0, originalOwner: "uk",
    x: 831, y: 48, neighbors: ["sz_3"] },
  { id: "morocco", name: "Morocco", terrain: "land", ipc: 1, originalOwner: "germany",
    x: 696, y: 999, neighbors: ["algeria","sahara","sz_13","sz_14"] },
  { id: "algeria", name: "Algeria", terrain: "land", ipc: 1, originalOwner: "germany",
    x: 798, y: 1008, neighbors: ["libya","morocco","sahara","sz_14"] },
  { id: "libya", name: "Libya", terrain: "land", ipc: 1, originalOwner: "germany",
    x: 1020, y: 1057, neighbors: ["algeria","egypt","sahara","sz_15"] },
  { id: "sahara", name: "Sahara", terrain: "land", ipc: 0, originalOwner: "germany",
    x: 1036, y: 1156, neighbors: ["algeria","anglo_egyptian_sudan","egypt","french_equatorial_africa","french_west_africa","libya","morocco","sz_23"] },
  { id: "french_west_africa", name: "Fr. W. Africa", terrain: "land", ipc: 1, originalOwner: "germany",
    x: 719, y: 1260, neighbors: ["french_equatorial_africa","sahara","sz_23"] },
  { id: "french_equatorial_africa", name: "Fr. Eq. Africa", terrain: "land", ipc: 1, originalOwner: "germany",
    x: 962, y: 1317, neighbors: ["anglo_egyptian_sudan","belgian_congo","french_west_africa","sahara","sz_24"] },
  { id: "anglo_egyptian_sudan", name: "Anglo-Egypt Sudan", terrain: "land", ipc: 0, originalOwner: "uk",
    x: 1181, y: 1299, neighbors: ["belgian_congo","egypt","french_equatorial_africa","italian_east_africa","rhodesia","sahara","sz_34"] },
  { id: "belgian_congo", name: "Belgian Congo", terrain: "land", ipc: 1, originalOwner: "uk",
    x: 1077, y: 1533, neighbors: ["anglo_egyptian_sudan","angola","french_equatorial_africa","rhodesia","south_africa","sz_24"] },
  { id: "italian_east_africa", name: "Ital. E. Africa", terrain: "land", ipc: 1, originalOwner: "uk",
    x: 1381, y: 1412, neighbors: ["anglo_egyptian_sudan","rhodesia","sz_33","sz_34"] },
  { id: "rhodesia", name: "Rhodesia", terrain: "land", ipc: 1, originalOwner: "uk",
    x: 1213, y: 1606, neighbors: ["anglo_egyptian_sudan","belgian_congo","italian_east_africa","mozambique","south_africa","sz_33"] },
  { id: "mozambique", name: "Mozambique", terrain: "land", ipc: 0, originalOwner: "uk",
    x: 1255, y: 1774, neighbors: ["rhodesia","south_africa","sz_28","sz_33"] },
  { id: "angola", name: "Angola", terrain: "land", ipc: 0, originalOwner: undefined,
    x: 1085, y: 1748, neighbors: ["belgian_congo","south_africa","sz_27"] },
  { id: "south_africa", name: "S. Africa", terrain: "land", ipc: 2, originalOwner: "uk",
    x: 1146, y: 1843, neighbors: ["angola","belgian_congo","mozambique","rhodesia","sz_27","sz_28"] },
  { id: "madagascar", name: "Madagascar", terrain: "land", ipc: 1, originalOwner: "uk",
    x: 1384, y: 1819, neighbors: ["sz_28","sz_29","sz_32","sz_33"] },
  { id: "egypt", name: "Egypt", terrain: "land", ipc: 2, originalOwner: "uk",
    x: 1225, y: 1100, neighbors: ["anglo_egyptian_sudan","libya","middle_east","sahara","sz_17","sz_34"] },
  { id: "middle_east", name: "Trans-Jordan", terrain: "land", ipc: 1, originalOwner: "uk",
    x: 1469, y: 1014, neighbors: ["egypt","persia","saudi_arabia","sz_17","sz_34","turkey"] },
  { id: "saudi_arabia", name: "Saudi Arabia", terrain: "land", ipc: 0, originalOwner: undefined,
    x: 1518, y: 1139, neighbors: ["middle_east","sz_34"] },
  { id: "turkey", name: "Turkey", terrain: "land", ipc: 0, originalOwner: undefined,
    x: 1465, y: 929, neighbors: ["balkans","caucasus","middle_east","persia","southern_europe","sz_15","sz_16","sz_17"] },
  { id: "persia", name: "Persia", terrain: "land", ipc: 1, originalOwner: "uk",
    x: 1683, y: 938, neighbors: ["afghanistan","caucasus","india","kazakh","middle_east","sz_34","turkey"] },
  { id: "afghanistan", name: "Afghanistan", terrain: "land", ipc: 0, originalOwner: "uk",
    x: 1843, y: 879, neighbors: ["himalaya","india","kazakh","persia","szechwan"] },
  { id: "united_kingdom", name: "United Kingdom", terrain: "land", ipc: 8, originalOwner: "uk",
    x: 815, y: 343, neighbors: ["eire","sz_6","sz_7","sz_8"] },
  { id: "eastern_canada", name: "E. Canada", terrain: "land", ipc: 3, originalOwner: "uk",
    x: 273, y: 415, neighbors: ["central_united_states","eastern_united_states","sz_1","sz_10","western_canada"] },
  { id: "western_canada", name: "W. Canada", terrain: "land", ipc: 1, originalOwner: "uk",
    x: 3362, y: 366, neighbors: ["alaska","eastern_canada","sz_65","western_united_states"] },
  { id: "greenland", name: "Greenland", terrain: "land", ipc: 0, originalOwner: "uk",
    x: 390, y: 74, neighbors: ["sz_2"] },
  { id: "west_indies", name: "W. Indies", terrain: "land", ipc: 1, originalOwner: "uk",
    x: 278, y: 963, neighbors: ["sz_18"] },
  { id: "brazil", name: "Brazil", terrain: "land", ipc: 3, originalOwner: "uk",
    x: 346, y: 1277, neighbors: ["colombia_equador","peru_argentina","sz_22","venezuela"] },
  { id: "colombia_equador", name: "Colombia/Ecuador", terrain: "land", ipc: 0, originalOwner: "uk",
    x: 97, y: 1170, neighbors: ["brazil","central_america","peru_argentina","sz_18","sz_19","venezuela"] },
  { id: "venezuela", name: "Venezuela", terrain: "land", ipc: 0, originalOwner: "uk",
    x: 204, y: 1084, neighbors: ["brazil","colombia_equador","sz_18"] },
  { id: "peru_argentina", name: "Peru/Argentina", terrain: "land", ipc: 0, originalOwner: "uk",
    x: 227, y: 1375, neighbors: ["brazil","chile","colombia_equador","sz_19","sz_21"] },
  { id: "chile", name: "Chile", terrain: "land", ipc: 0, originalOwner: "uk",
    x: 185, y: 1547, neighbors: ["peru_argentina","sz_20","sz_21"] },
  { id: "central_america", name: "Central America", terrain: "land", ipc: 1, originalOwner: "usa",
    x: 70, y: 990, neighbors: ["colombia_equador","east_mexico","sz_18","sz_19"] },
  { id: "eastern_united_states", name: "E. United States", terrain: "land", ipc: 12, originalOwner: "usa",
    x: 0, y: 0, neighbors: ["central_united_states","eastern_canada","sz_11"] },
  { id: "central_united_states", name: "C. United States", terrain: "land", ipc: 6, originalOwner: "usa",
    x: 0, y: 0, neighbors: ["east_mexico","eastern_canada","eastern_united_states","sz_11","western_united_states"] },
  { id: "western_united_states", name: "W. United States", terrain: "land", ipc: 10, originalOwner: "usa",
    x: 0, y: 0, neighbors: ["central_united_states","mexico","sz_56","western_canada"] },
  { id: "east_mexico", name: "E. Mexico", terrain: "land", ipc: 0, originalOwner: "usa",
    x: 24, y: 891, neighbors: ["central_america","central_united_states","mexico","sz_11","sz_18","sz_19"] },
  { id: "mexico", name: "Mexico", terrain: "land", ipc: 2, originalOwner: "usa",
    x: 3439, y: 816, neighbors: ["east_mexico","sz_55","western_united_states"] },
  { id: "alaska", name: "Alaska", terrain: "land", ipc: 2, originalOwner: "usa",
    x: 3161, y: 248, neighbors: ["sz_64","sz_65","western_canada"] },
  { id: "hawaii", name: "Hawaii", terrain: "land", ipc: 1, originalOwner: "usa",
    x: 3202, y: 1055, neighbors: ["sz_53"] },
  { id: "india", name: "India", terrain: "land", ipc: 3, originalOwner: "uk",
    x: 1884, y: 1044, neighbors: ["afghanistan","burma","himalaya","persia","sz_35"] },
  { id: "burma", name: "Burma", terrain: "land", ipc: 1, originalOwner: "japan",
    x: 2160, y: 1025, neighbors: ["french_indochina","himalaya","india","sz_36","yunnan"] },
  { id: "malaya", name: "Malaya", terrain: "land", ipc: 1, originalOwner: "japan",
    x: 2207, y: 1237, neighbors: ["french_indochina","sz_36"] },
  { id: "himalaya", name: "Himalaya", terrain: "land", ipc: 0, originalOwner: "japan",
    x: 2048, y: 880, neighbors: ["afghanistan","burma","india","szechwan","yunnan"] },
  { id: "french_indochina", name: "Fr. Indochina", terrain: "land", ipc: 2, originalOwner: "japan",
    x: 2244, y: 1101, neighbors: ["burma","malaya","sz_36","yunnan"] },
  { id: "yunnan", name: "Yunnan", terrain: "land", ipc: 1, originalOwner: "japan",
    x: 2254, y: 919, neighbors: ["burma","french_indochina","himalaya","kwangtung","sz_61","szechwan"] },
  { id: "szechwan", name: "Szechwan", terrain: "land", ipc: 1, originalOwner: "japan",
    x: 2089, y: 770, neighbors: ["afghanistan","anhwei","himalaya","kazakh","kwangtung","sinkiang","yunnan"] },
  { id: "anhwei", name: "Anhwei", terrain: "land", ipc: 1, originalOwner: "japan",
    x: 2284, y: 685, neighbors: ["kiangsu","kwangtung","manchuria","mongolia","sinkiang","szechwan"] },
  { id: "kiangsu", name: "Kiangsu", terrain: "land", ipc: 2, originalOwner: "japan",
    x: 2448, y: 757, neighbors: ["anhwei","kwangtung","manchuria","sz_61"] },
  { id: "kwangtung", name: "Kwangtung", terrain: "land", ipc: 2, originalOwner: "japan",
    x: 2394, y: 903, neighbors: ["anhwei","kiangsu","sz_61","szechwan","yunnan"] },
  { id: "manchuria", name: "Manchuria", terrain: "land", ipc: 3, originalOwner: "japan",
    x: 2560, y: 552, neighbors: ["anhwei","buryatia","kiangsu","mongolia","sz_62"] },
  { id: "japan", name: "Japan", terrain: "land", ipc: 8, originalOwner: "japan",
    x: 2748, y: 716, neighbors: ["sz_60","sz_62"] },
  { id: "okinawa", name: "Okinawa", terrain: "land", ipc: 0, originalOwner: "japan",
    x: 2725, y: 1105, neighbors: ["sz_51"] },
  { id: "iwo_jima", name: "Iwo Jima", terrain: "land", ipc: 0, originalOwner: "japan",
    x: 2939, y: 863, neighbors: ["sz_59"] },
  { id: "formosa", name: "Formosa", terrain: "land", ipc: 0, originalOwner: "japan",
    x: 2486, y: 998, neighbors: ["sz_61"] },
  { id: "philippines", name: "Philippines", terrain: "land", ipc: 3, originalOwner: "japan",
    x: 2545, y: 1172, neighbors: ["sz_48"] },
  { id: "borneo", name: "Borneo", terrain: "land", ipc: 4, originalOwner: "japan",
    x: 2436, y: 1385, neighbors: ["sz_47"] },
  { id: "east_indies", name: "East Indies", terrain: "land", ipc: 4, originalOwner: "japan",
    x: 2210, y: 1451, neighbors: ["sz_37"] },
  { id: "caroline_islands", name: "Caroline Is.", terrain: "land", ipc: 0, originalOwner: "japan",
    x: 0, y: 0, neighbors: ["sz_50"] },
  { id: "new_guinea", name: "New Guinea", terrain: "land", ipc: 1, originalOwner: "uk",
    x: 2735, y: 1537, neighbors: ["sz_49"] },
  { id: "solomon_islands", name: "Solomon Is.", terrain: "land", ipc: 0, originalOwner: "uk",
    x: 0, y: 0, neighbors: ["sz_44"] },
  { id: "eastern_australia", name: "E. Australia", terrain: "land", ipc: 1, originalOwner: "uk",
    x: 2790, y: 1866, neighbors: ["sz_39","sz_45","western_australia"] },
  { id: "western_australia", name: "W. Australia", terrain: "land", ipc: 1, originalOwner: "uk",
    x: 2620, y: 1769, neighbors: ["eastern_australia","sz_38","sz_46"] },
  { id: "new_zealand", name: "New Zealand", terrain: "land", ipc: 1, originalOwner: "uk",
    x: 3077, y: 1853, neighbors: ["sz_40"] },
  { id: "wake_island", name: "Wake Island", terrain: "land", ipc: 0, originalOwner: "japan",
    x: 2927, y: 1105, neighbors: ["sz_52"] },
  { id: "midway", name: "Midway", terrain: "land", ipc: 0, originalOwner: undefined,
    x: 3133, y: 613, neighbors: ["sz_57"] },
  // ========= SEA ZONES =========
  { id: "sz_1", name: "Sea Zone 1", terrain: "sea", ipc: 0,
    x: 249, y: 156, neighbors: ["eastern_canada","sz_10","sz_2"] },
  { id: "sz_2", name: "Sea Zone 2", terrain: "sea", ipc: 0,
    x: 498, y: 170, neighbors: ["greenland","sz_1","sz_10","sz_3","sz_7","sz_9"] },
  { id: "sz_3", name: "Sea Zone 3", terrain: "sea", ipc: 0,
    x: 810, y: 94, neighbors: ["finland","iceland","norway","sz_2","sz_4","sz_6","sz_7"] },
  { id: "sz_4", name: "Sea Zone 4", terrain: "sea", ipc: 0,
    x: 1462, y: 40, neighbors: ["archangel","karelia","sz_3"] },
  { id: "sz_5", name: "Sea Zone 5", terrain: "sea", ipc: 0,
    x: 1051, y: 409, neighbors: ["baltic_states","finland","germany_terr","karelia","northern_europe","norway","sweden","sz_6"] },
  { id: "sz_6", name: "Sea Zone 6", terrain: "sea", ipc: 0,
    x: 862, y: 254, neighbors: ["northern_europe","norway","sz_3","sz_5","sz_7","sz_8","united_kingdom"] },
  { id: "sz_7", name: "Sea Zone 7", terrain: "sea", ipc: 0,
    x: 663, y: 223, neighbors: ["eire","sz_2","sz_3","sz_6","sz_8","sz_9","united_kingdom"] },
  { id: "sz_8", name: "Sea Zone 8", terrain: "sea", ipc: 0,
    x: 745, y: 475, neighbors: ["eire","france","northern_europe","sz_13","sz_6","sz_7","sz_9","united_kingdom"] },
  { id: "sz_9", name: "Sea Zone 9", terrain: "sea", ipc: 0,
    x: 542, y: 512, neighbors: ["sz_10","sz_12","sz_13","sz_2","sz_7","sz_8"] },
  { id: "sz_10", name: "Sea Zone 10", terrain: "sea", ipc: 0,
    x: 403, y: 599, neighbors: ["eastern_canada","sz_1","sz_11","sz_12","sz_2","sz_9"] },
  { id: "sz_11", name: "Sea Zone 11", terrain: "sea", ipc: 0,
    x: 270, y: 767, neighbors: ["central_united_states","east_mexico","eastern_united_states","sz_10","sz_12","sz_18"] },
  { id: "sz_12", name: "Sea Zone 12", terrain: "sea", ipc: 0,
    x: 407, y: 847, neighbors: ["sz_10","sz_11","sz_13","sz_18","sz_22","sz_23","sz_9"] },
  { id: "sz_13", name: "Sea Zone 13", terrain: "sea", ipc: 0,
    x: 568, y: 961, neighbors: ["gibraltar","morocco","spain_portugal","sz_12","sz_14","sz_23","sz_8","sz_9"] },
  { id: "sz_14", name: "Sea Zone 14", terrain: "sea", ipc: 0,
    x: 775, y: 919, neighbors: ["algeria","france","gibraltar","morocco","spain_portugal","sz_13","sz_15"] },
  { id: "sz_15", name: "Sea Zone 15", terrain: "sea", ipc: 0,
    x: 1004, y: 938, neighbors: ["italy","libya","southern_europe","sz_14","sz_16","sz_17","turkey"] },
  { id: "sz_16", name: "Sea Zone 16", terrain: "sea", ipc: 0,
    x: 1417, y: 831, neighbors: ["balkans","caucasus","sz_15","turkey","ukraine"] },
  { id: "sz_17", name: "Sea Zone 17", terrain: "sea", ipc: 0,
    x: 1255, y: 992, neighbors: ["egypt","middle_east","sz_15","sz_34","turkey"] },
  { id: "sz_18", name: "Sea Zone 18", terrain: "sea", ipc: 0,
    x: 280, y: 1025, neighbors: ["central_america","colombia_equador","east_mexico","sz_11","sz_12","sz_19","sz_22","venezuela","west_indies"] },
  { id: "sz_19", name: "Sea Zone 19", terrain: "sea", ipc: 0,
    x: 41, y: 1053, neighbors: ["central_america","colombia_equador","east_mexico","peru_argentina","sz_18","sz_20","sz_55"] },
  { id: "sz_20", name: "Sea Zone 20", terrain: "sea", ipc: 0,
    x: 75, y: 1506, neighbors: ["chile","sz_19","sz_21","sz_42"] },
  { id: "sz_21", name: "Sea Zone 21", terrain: "sea", ipc: 0,
    x: 223, y: 1800, neighbors: ["chile","peru_argentina","sz_20","sz_22","sz_25","sz_26","sz_41"] },
  { id: "sz_22", name: "Sea Zone 22", terrain: "sea", ipc: 0,
    x: 447, y: 1470, neighbors: ["brazil","sz_12","sz_18","sz_21","sz_23","sz_25"] },
  { id: "sz_23", name: "Sea Zone 23", terrain: "sea", ipc: 0,
    x: 587, y: 1437, neighbors: ["french_west_africa","sahara","sz_12","sz_13","sz_22","sz_24","sz_25"] },
  { id: "sz_24", name: "Sea Zone 24", terrain: "sea", ipc: 0,
    x: 905, y: 1526, neighbors: ["belgian_congo","french_equatorial_africa","sz_23","sz_25","sz_27"] },
  { id: "sz_25", name: "Sea Zone 25", terrain: "sea", ipc: 0,
    x: 595, y: 1701, neighbors: ["sz_21","sz_22","sz_23","sz_24","sz_26","sz_27"] },
  { id: "sz_26", name: "Sea Zone 26", terrain: "sea", ipc: 0,
    x: 609, y: 1862, neighbors: ["sz_21","sz_25","sz_27"] },
  { id: "sz_27", name: "Sea Zone 27", terrain: "sea", ipc: 0,
    x: 970, y: 1836, neighbors: ["angola","south_africa","sz_24","sz_25","sz_26","sz_28"] },
  { id: "sz_28", name: "Sea Zone 28", terrain: "sea", ipc: 0,
    x: 1284, y: 1871, neighbors: ["madagascar","mozambique","south_africa","sz_27","sz_29","sz_33"] },
  { id: "sz_29", name: "Sea Zone 29", terrain: "sea", ipc: 0,
    x: 1589, y: 1880, neighbors: ["madagascar","sz_28","sz_30","sz_31","sz_32"] },
  { id: "sz_30", name: "Sea Zone 30", terrain: "sea", ipc: 0,
    x: 1946, y: 1881, neighbors: ["sz_29","sz_31","sz_37","sz_38"] },
  { id: "sz_31", name: "Sea Zone 31", terrain: "sea", ipc: 0,
    x: 1925, y: 1552, neighbors: ["sz_29","sz_30","sz_32","sz_35","sz_37"] },
  { id: "sz_32", name: "Sea Zone 32", terrain: "sea", ipc: 0,
    x: 1682, y: 1601, neighbors: ["madagascar","sz_29","sz_31","sz_33","sz_34","sz_35"] },
  { id: "sz_33", name: "Sea Zone 33", terrain: "sea", ipc: 0,
    x: 1423, y: 1579, neighbors: ["italian_east_africa","madagascar","mozambique","rhodesia","sz_28","sz_32","sz_34"] },
  { id: "sz_34", name: "Sea Zone 34", terrain: "sea", ipc: 0,
    x: 1558, y: 1289, neighbors: ["anglo_egyptian_sudan","egypt","italian_east_africa","middle_east","persia","saudi_arabia","sz_17","sz_32","sz_33","sz_35"] },
  { id: "sz_35", name: "Sea Zone 35", terrain: "sea", ipc: 0,
    x: 1910, y: 1322, neighbors: ["india","sz_31","sz_32","sz_34","sz_36","sz_37"] },
  { id: "sz_36", name: "Sea Zone 36", terrain: "sea", ipc: 0,
    x: 2345, y: 1228, neighbors: ["burma","french_indochina","malaya","sz_35","sz_37","sz_47","sz_48","sz_61"] },
  { id: "sz_37", name: "Sea Zone 37", terrain: "sea", ipc: 0,
    x: 2175, y: 1536, neighbors: ["east_indies","sz_30","sz_31","sz_35","sz_36","sz_38","sz_46","sz_47"] },
  { id: "sz_38", name: "Sea Zone 38", terrain: "sea", ipc: 0,
    x: 2345, y: 1888, neighbors: ["sz_30","sz_37","sz_39","sz_46","western_australia"] },
  { id: "sz_39", name: "Sea Zone 39", terrain: "sea", ipc: 0,
    x: 2974, y: 1884, neighbors: ["eastern_australia","sz_38","sz_40","sz_45"] },
  { id: "sz_40", name: "Sea Zone 40", terrain: "sea", ipc: 0,
    x: 3177, y: 1774, neighbors: ["new_zealand","sz_39","sz_41","sz_43","sz_44","sz_45"] },
  { id: "sz_41", name: "Sea Zone 41", terrain: "sea", ipc: 0,
    x: 3337, y: 1754, neighbors: ["sz_21","sz_40","sz_42","sz_43"] },
  { id: "sz_42", name: "Sea Zone 42", terrain: "sea", ipc: 0,
    x: 3386, y: 1395, neighbors: ["sz_20","sz_41","sz_43","sz_54","sz_55"] },
  { id: "sz_43", name: "Sea Zone 43", terrain: "sea", ipc: 0,
    x: 3250, y: 1398, neighbors: ["sz_40","sz_41","sz_42","sz_44","sz_53","sz_54"] },
  { id: "sz_44", name: "Sea Zone 44", terrain: "sea", ipc: 0,
    x: 3007, y: 1378, neighbors: ["solomon_islands","sz_40","sz_43","sz_45","sz_49","sz_50","sz_52","sz_53"] },
  { id: "sz_45", name: "Sea Zone 45", terrain: "sea", ipc: 0,
    x: 2917, y: 1665, neighbors: ["eastern_australia","sz_39","sz_40","sz_44","sz_46","sz_49"] },
  { id: "sz_46", name: "Sea Zone 46", terrain: "sea", ipc: 0,
    x: 2465, y: 1664, neighbors: ["sz_37","sz_38","sz_45","sz_47","sz_49","western_australia"] },
  { id: "sz_47", name: "Sea Zone 47", terrain: "sea", ipc: 0,
    x: 2457, y: 1505, neighbors: ["borneo","sz_36","sz_37","sz_46","sz_48","sz_49"] },
  { id: "sz_48", name: "Sea Zone 48", terrain: "sea", ipc: 0,
    x: 2564, y: 1079, neighbors: ["philippines","sz_36","sz_47","sz_49","sz_50","sz_51","sz_60","sz_61"] },
  { id: "sz_49", name: "Sea Zone 49", terrain: "sea", ipc: 0,
    x: 2692, y: 1452, neighbors: ["new_guinea","sz_44","sz_45","sz_46","sz_47","sz_48","sz_50"] },
  { id: "sz_50", name: "Sea Zone 50", terrain: "sea", ipc: 0,
    x: 2765, y: 1226, neighbors: ["caroline_islands","sz_44","sz_48","sz_49","sz_51","sz_52"] },
  { id: "sz_51", name: "Sea Zone 51", terrain: "sea", ipc: 0,
    x: 2740, y: 991, neighbors: ["okinawa","sz_48","sz_50","sz_52","sz_59","sz_60"] },
  { id: "sz_52", name: "Sea Zone 52", terrain: "sea", ipc: 0,
    x: 2921, y: 1032, neighbors: ["sz_44","sz_50","sz_51","sz_53","sz_57","sz_59","wake_island"] },
  { id: "sz_53", name: "Sea Zone 53", terrain: "sea", ipc: 0,
    x: 3110, y: 1114, neighbors: ["hawaii","sz_43","sz_44","sz_52","sz_54","sz_56","sz_57"] },
  { id: "sz_54", name: "Sea Zone 54", terrain: "sea", ipc: 0,
    x: 3312, y: 1074, neighbors: ["sz_42","sz_43","sz_53","sz_55","sz_56"] },
  { id: "sz_55", name: "Sea Zone 55", terrain: "sea", ipc: 0,
    x: 3434, y: 962, neighbors: ["mexico","sz_19","sz_42","sz_54","sz_56"] },
  { id: "sz_56", name: "Sea Zone 56", terrain: "sea", ipc: 0,
    x: 3219, y: 734, neighbors: ["sz_53","sz_54","sz_55","sz_57","sz_65","western_united_states"] },
  { id: "sz_57", name: "Sea Zone 57", terrain: "sea", ipc: 0,
    x: 3074, y: 763, neighbors: ["midway","sz_52","sz_53","sz_56","sz_58","sz_59","sz_64","sz_65"] },
  { id: "sz_58", name: "Sea Zone 58", terrain: "sea", ipc: 0,
    x: 2935, y: 618, neighbors: ["sz_57","sz_59","sz_60","sz_63","sz_64"] },
  { id: "sz_59", name: "Sea Zone 59", terrain: "sea", ipc: 0,
    x: 2913, y: 809, neighbors: ["iwo_jima","sz_51","sz_52","sz_57","sz_58","sz_60"] },
  { id: "sz_60", name: "Sea Zone 60", terrain: "sea", ipc: 0,
    x: 2787, y: 787, neighbors: ["japan","sz_48","sz_51","sz_58","sz_59","sz_61","sz_62","sz_63"] },
  { id: "sz_61", name: "Sea Zone 61", terrain: "sea", ipc: 0,
    x: 2492, y: 936, neighbors: ["formosa","kiangsu","kwangtung","sz_36","sz_48","sz_60","sz_62","yunnan"] },
  { id: "sz_62", name: "Sea Zone 62", terrain: "sea", ipc: 0,
    x: 2656, y: 641, neighbors: ["buryatia","japan","manchuria","sz_60","sz_61","sz_63"] },
  { id: "sz_63", name: "Sea Zone 63", terrain: "sea", ipc: 0,
    x: 2893, y: 388, neighbors: ["buryatia","soviet_far_east","sz_58","sz_60","sz_62","sz_64"] },
  { id: "sz_64", name: "Sea Zone 64", terrain: "sea", ipc: 0,
    x: 3028, y: 426, neighbors: ["alaska","sz_57","sz_58","sz_63","sz_65"] },
  { id: "sz_65", name: "Sea Zone 65", terrain: "sea", ipc: 0,
    x: 3188, y: 444, neighbors: ["alaska","sz_56","sz_57","sz_64","western_canada"] },
];

export const TERRITORY_MAP: Record<string, Territory> =
  Object.fromEntries(TERRITORIES.map((t) => [t.id, t]));

export interface StartingUnit {
  territory: string;
  owner: PowerId;
  units: Partial<Record<UnitId, number>>;
}

export const STARTING_SETUP: StartingUnit[] = [
  { territory: "russia", owner: "russia", units: { infantry: 4, artillery: 1, tank: 2, fighter: 1, factory: 1, aa: 1 } },
  { territory: "karelia", owner: "russia", units: { infantry: 3, aa: 1 } },
  { territory: "ukraine", owner: "russia", units: { infantry: 3, artillery: 1 } },
  { territory: "caucasus", owner: "russia", units: { infantry: 3, tank: 1, factory: 1, aa: 1 } },
  { territory: "archangel", owner: "russia", units: { infantry: 1 } },
  { territory: "vologda", owner: "russia", units: { infantry: 2 } },
  { territory: "west_russia", owner: "russia", units: { infantry: 2 } },
  { territory: "belorussia", owner: "russia", units: { infantry: 2 } },
  { territory: "baltic_states", owner: "russia", units: { infantry: 1 } },
  { territory: "evenki", owner: "russia", units: { infantry: 1 } },
  { territory: "novosibirsk", owner: "russia", units: { infantry: 1 } },
  { territory: "buryatia", owner: "russia", units: { infantry: 1 } },
  { territory: "yakut", owner: "russia", units: { infantry: 1 } },
  { territory: "soviet_far_east", owner: "russia", units: { infantry: 1 } },
  { territory: "sinkiang", owner: "russia", units: { infantry: 1 } },
  { territory: "mongolia", owner: "russia", units: { infantry: 1 } },
  { territory: "kazakh", owner: "russia", units: { infantry: 2 } },
  { territory: "sz_4", owner: "russia", units: { destroyer: 1, submarine: 1 } },
  { territory: "germany_terr", owner: "germany", units: { infantry: 4, artillery: 1, tank: 2, fighter: 2, bomber: 1, aa: 1, factory: 1 } },
  { territory: "northern_europe", owner: "germany", units: { infantry: 2, artillery: 1, tank: 1 } },
  { territory: "southern_europe", owner: "germany", units: { infantry: 2, fighter: 1, factory: 1 } },
  { territory: "france", owner: "germany", units: { infantry: 2, tank: 1 } },
  { territory: "poland", owner: "germany", units: { infantry: 2 } },
  { territory: "balkans", owner: "germany", units: { infantry: 1 } },
  { territory: "norway", owner: "germany", units: { infantry: 2 } },
  { territory: "finland", owner: "germany", units: { infantry: 2 } },
  { territory: "italy", owner: "germany", units: { infantry: 2, artillery: 1 } },
  { territory: "libya", owner: "germany", units: { infantry: 1, tank: 1 } },
  { territory: "algeria", owner: "germany", units: { infantry: 1 } },
  { territory: "french_west_africa", owner: "germany", units: { infantry: 1 } },
  { territory: "sz_5", owner: "germany", units: { submarine: 1, transport: 1 } },
  { territory: "sz_15", owner: "germany", units: { cruiser: 1, transport: 1 } },
  { territory: "united_kingdom", owner: "uk", units: { infantry: 2, artillery: 1, tank: 1, fighter: 2, bomber: 1, aa: 1, factory: 1 } },
  { territory: "eastern_canada", owner: "uk", units: { infantry: 1 } },
  { territory: "india", owner: "uk", units: { infantry: 2, artillery: 1, fighter: 1, factory: 1 } },
  { territory: "egypt", owner: "uk", units: { infantry: 1, tank: 1 } },
  { territory: "eastern_australia", owner: "uk", units: { infantry: 1, fighter: 1 } },
  { territory: "south_africa", owner: "uk", units: { infantry: 1 } },
  { territory: "new_zealand", owner: "uk", units: { infantry: 1 } },
  { territory: "middle_east", owner: "uk", units: { infantry: 1 } },
  { territory: "persia", owner: "uk", units: { infantry: 1 } },
  { territory: "afghanistan", owner: "uk", units: { infantry: 1 } },
  { territory: "italian_east_africa", owner: "uk", units: { infantry: 1 } },
  { territory: "belgian_congo", owner: "uk", units: { infantry: 1 } },
  { territory: "rhodesia", owner: "uk", units: { infantry: 1 } },
  { territory: "madagascar", owner: "uk", units: { infantry: 1 } },
  { territory: "solomon_islands", owner: "uk", units: { infantry: 1 } },
  { territory: "brazil", owner: "uk", units: { infantry: 1 } },
  { territory: "sz_7", owner: "uk", units: { battleship: 1, destroyer: 1, transport: 1 } },
  { territory: "sz_8", owner: "uk", units: { cruiser: 1 } },
  { territory: "sz_35", owner: "uk", units: { destroyer: 1, transport: 1 } },
  { territory: "japan", owner: "japan", units: { infantry: 3, artillery: 1, fighter: 2, aa: 1, factory: 1 } },
  { territory: "manchuria", owner: "japan", units: { infantry: 3, artillery: 1 } },
  { territory: "french_indochina", owner: "japan", units: { infantry: 2, tank: 1 } },
  { territory: "kwangtung", owner: "japan", units: { infantry: 2 } },
  { territory: "kiangsu", owner: "japan", units: { infantry: 2 } },
  { territory: "anhwei", owner: "japan", units: { infantry: 1 } },
  { territory: "szechwan", owner: "japan", units: { infantry: 1 } },
  { territory: "yunnan", owner: "japan", units: { infantry: 1 } },
  { territory: "philippines", owner: "japan", units: { infantry: 1 } },
  { territory: "east_indies", owner: "japan", units: { infantry: 1 } },
  { territory: "borneo", owner: "japan", units: { infantry: 1 } },
  { territory: "new_guinea", owner: "japan", units: { infantry: 1 } },
  { territory: "iwo_jima", owner: "japan", units: { infantry: 1 } },
  { territory: "okinawa", owner: "japan", units: { infantry: 1 } },
  { territory: "caroline_islands", owner: "japan", units: { infantry: 1 } },
  { territory: "wake_island", owner: "japan", units: { infantry: 1 } },
  { territory: "sz_60", owner: "japan", units: { battleship: 1, carrier: 1, fighter: 1, destroyer: 1, submarine: 1, transport: 1 } },
  { territory: "sz_62", owner: "japan", units: { cruiser: 1, transport: 1 } },
  { territory: "eastern_united_states", owner: "usa", units: { infantry: 3, artillery: 1, tank: 1, fighter: 1, bomber: 1, aa: 1, factory: 1 } },
  { territory: "central_united_states", owner: "usa", units: { infantry: 1 } },
  { territory: "western_united_states", owner: "usa", units: { infantry: 2, tank: 1, fighter: 1, factory: 1 } },
  { territory: "alaska", owner: "usa", units: { infantry: 1 } },
  { territory: "hawaii", owner: "usa", units: { infantry: 1 } },
  { territory: "mexico", owner: "usa", units: { infantry: 1 } },
  { territory: "sz_11", owner: "usa", units: { battleship: 1, transport: 1 } },
  { territory: "sz_53", owner: "usa", units: { carrier: 1, fighter: 1, destroyer: 1, submarine: 1, transport: 1 } },
];
